title = "hugodelab"
languageCode = "ja"
defaultContentLanguage = "ja"
baseURL = "http://localhost:1313/"
enableGitInfo = true
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodefences = true
enableRobotsTXT = true
googleAnalytics = "UA-XXXXXXXXX-X"

[params]
  logo = "https://bulma.io/images/bulma-logo.png"
  title = "Hugo de Lab"

[taxonomies]
  category = "categories"
  level = "level"